// <auto-generated />
using System;
using ArduinoWebApp.Acsses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArduinoWebApp.Acsses.Migrations
{
    [DbContext(typeof(ArduinoAppDbContext))]
    partial class ArduinoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArduinoWebApp.Model.TbLdrSensorReading", b =>
                {
                    b.Property<int>("LdrSensorReadingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LdrSensorReadingID"));

                    b.Property<float>("LdrSensorReadingAvratgeValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("LdrSensorReadingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LdrSensorReadingID");

                    b.ToTable("TbLdrSensorReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
